# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

downInPutMC <- function(nSim, S0, K, r, sigma, T, B) {
    .Call(`_downInPutMC_downInPutMC`, nSim, S0, K, r, sigma, T, B)
}

rcpp_hello <- function() {
    .Call(`_downInPutMC_rcpp_hello`)
}

